from pathlib import Path
import unittest


ROOT = Path(__file__).resolve().parents[1]
INDEX = (ROOT / "web" / "static" / "index.html").read_text(encoding="utf-8")
SCRIPT = (ROOT / "web" / "static" / "workspace-tabs.js").read_text(encoding="utf-8")
STYLE = (ROOT / "web" / "static" / "workspace-tabs.css").read_text(encoding="utf-8")
SUBSCRIPTION_SCRIPT = (ROOT / "web" / "static" / "subscription-admin.js").read_text(encoding="utf-8")
SUBSCRIPTION_STYLE = (ROOT / "web" / "static" / "subscription-admin.css").read_text(encoding="utf-8")
AUTH_SCRIPT = (ROOT / "web" / "static" / "auth-client.js").read_text(encoding="utf-8")
ORGANIZATION_SCRIPT = (ROOT / "web" / "static" / "organization-admin.js").read_text(encoding="utf-8")
ORGANIZATION_STYLE = (ROOT / "web" / "static" / "organization-admin.css").read_text(encoding="utf-8")
NEWS_REVIEW_STYLE = (ROOT / "web" / "static" / "news-review-sheet.css").read_text(encoding="utf-8")
WEB_APP = (ROOT / "web_app.py").read_text(encoding="utf-8")


class WorkspaceTabsTests(unittest.TestCase):
    def test_user_facing_ai_copy_does_not_say_company_intranet(self):
        self.assertNotIn("公司内网", INDEX)
        self.assertNotIn("公司内网", WEB_APP)
        self.assertNotIn("内网 AI", WEB_APP)
        self.assertIn("AI 模型网关", INDEX)

    def test_dashboard_and_five_modules_have_accessible_tabs_and_panels(self):
        modules = (
            "dashboard",
            "monitoring",
            "competitor",
            "intelligence-map",
            "news",
            "weekly",
            "performance",
            "review",
            "subscriptions",
            "ai",
            "log",
            "fault",
            "architecture",
            "organization",
            "footprint",
        )
        for module in modules:
            self.assertIn(f'id="workspace-tab-{module}"', INDEX)
            self.assertIn(f'aria-controls="workspace-panel-{module}"', INDEX)
            self.assertIn(f'id="workspace-panel-{module}"', INDEX)
            self.assertIn(f'data-workspace-panel="{module}"', INDEX)
        self.assertEqual(INDEX.count('role="tab"'), len(modules))
        self.assertEqual(INDEX.count('role="tabpanel"'), len(modules))
        dashboard_tab = INDEX[INDEX.index('id="workspace-tab-dashboard"'):INDEX.index('id="workspace-tab-monitoring"')]
        self.assertIn('<span class="workspace-tab-label">战略总览</span>', dashboard_tab)
        self.assertNotIn("驾驶舱", dashboard_tab)

    def test_auth_permissions_gate_tabs_requests_and_organization_admin(self):
        self.assertIn('/static/auth-client.js?v=5', INDEX)
        self.assertIn('/static/organization-admin.js?v=36', INDEX)
        self.assertIn('/static/organization-admin.css?v=29', INDEX)
        self.assertIn('/static/workspace-tabs.js?v=186', INDEX)
        self.assertIn('/static/app.js?v=323', INDEX)
        self.assertIn('await window.CMHKAuth?.ready', SCRIPT)
        self.assertIn('window.CMHKAuth?.hasModule(permissionModule(module))', SCRIPT)
        self.assertIn('definitions.filter(([, module]) => can(module))', SCRIPT)
        self.assertIn('iframe[data-src]', SCRIPT)
        self.assertIn('fetch("/api/auth/me"', AUTH_SCRIPT)
        self.assertIn('fetch("/api/auth/logout"', AUTH_SCRIPT)
        self.assertIn('id="authUserMenuButton"', INDEX)
        self.assertIn('id="authUserAvatarImage"', INDEX)
        self.assertIn('aria-haspopup="menu"', INDEX)
        self.assertIn('document.addEventListener("pointerdown"', AUTH_SCRIPT)
        self.assertIn('event.key === "Escape"', AUTH_SCRIPT)
        self.assertIn('打开账户菜单', AUTH_SCRIPT)
        self.assertIn('.auth-user-copy{display:none;', ORGANIZATION_STYLE)
        self.assertNotIn('.auth-user-copy,.auth-user-chevron{display:none}', ORGANIZATION_STYLE)
        self.assertIn('request("/api/auth/admin/users")', ORGANIZATION_SCRIPT)
        self.assertIn('/api/auth/admin/users/${encodeURIComponent(detail.dataset.userId)}', ORGANIZATION_SCRIPT)
        self.assertIn('/api/auth/admin/directory/search?q=${encodeURIComponent(query)}', ORGANIZATION_SCRIPT)
        self.assertIn('request("/api/auth/admin/users/import"', ORGANIZATION_SCRIPT)
        self.assertIn('request("/api/auth/admin/audit?limit=all")', ORGANIZATION_SCRIPT)
        self.assertIn("团队足迹", ORGANIZATION_SCRIPT)
        self.assertIn('data-workspace-tab="footprint"', INDEX)
        self.assertIn('{ footprint: "organization", "intelligence-map": "competitor", architecture: "dashboard" }[module] || module', SCRIPT)
        self.assertIn('class="organization-profile-card" role="dialog"', ORGANIZATION_SCRIPT)
        self.assertIn("data-select-user", ORGANIZATION_SCRIPT)
        self.assertIn("person.avatarUrl", ORGANIZATION_SCRIPT)
        self.assertIn("!user.developmentAccount", ORGANIZATION_SCRIPT)
        self.assertIn("data-delete-user", ORGANIZATION_SCRIPT)
        self.assertIn('method: "DELETE"', ORGANIZATION_SCRIPT)
        self.assertIn('data-directory-open aria-label="添加成员"', ORGANIZATION_SCRIPT)
        self.assertNotIn('>添加飞书成员</button>', ORGANIZATION_SCRIPT)
        self.assertIn('class="organization-add-member-icon"', ORGANIZATION_SCRIPT)
        self.assertNotIn('title="添加成员">＋</button>', ORGANIZATION_SCRIPT)
        self.assertIn('.organization-add-member-icon{width:22px;height:22px', ORGANIZATION_STYLE)
        self.assertNotIn('>刷新成员</button>', ORGANIZATION_SCRIPT)
        self.assertNotIn('class="organization-heading"', ORGANIZATION_SCRIPT)
        self.assertNotIn('ORGANIZATION &amp; ACCESS', ORGANIZATION_SCRIPT)
        self.assertIn('query.length < 2', ORGANIZATION_SCRIPT)
        self.assertIn('state.directory.controller?.abort()', ORGANIZATION_SCRIPT)
        self.assertIn('controller.abort(), 12000', ORGANIZATION_SCRIPT)
        self.assertIn('飞书通讯录搜索超时，请稍后重试。', ORGANIZATION_SCRIPT)
        self.assertIn('function highlightSearchMatch(value, query)', ORGANIZATION_SCRIPT)
        self.assertIn('class="organization-search-match"', ORGANIZATION_SCRIPT)
        self.assertIn('highlightSearchMatch(user.name || "未命名成员", directory.query)', ORGANIZATION_SCRIPT)
        self.assertIn('highlightSearchMatch([user.department, user.email]', ORGANIZATION_SCRIPT)
        self.assertIn('.organization-search-match', ORGANIZATION_STYLE)
        self.assertIn('<div><dt>员工岗位</dt><dd>${esc(user.title', ORGANIZATION_SCRIPT)
        self.assertNotIn('data-title maxlength="80"', ORGANIZATION_SCRIPT)
        self.assertNotIn('title: detail.querySelector("[data-title]").value', ORGANIZATION_SCRIPT)
        self.assertNotIn('修改岗位', ORGANIZATION_SCRIPT)
        self.assertNotIn('.organization-title-readonly', ORGANIZATION_STYLE)

    def test_modules_use_live_apis_and_existing_workflows(self):
        for endpoint in (
            "/api/status",
            "/api/company-metrics",
            "/api/strategic-briefs",
        ):
            self.assertIn(f'fetch("{endpoint}")', SCRIPT)
        for existing_action in (
            "#openNewsReviewSheetButton",
            "#generateButtonSecondary",
            "#generatePerformanceButton",
        ):
            self.assertIn(existing_action, SCRIPT)

    def test_workspace_requests_render_independently_without_a_global_data_barrier(self):
        self.assertIn('activeDefinitions.map(async ([key, module, request]) =>', SCRIPT)
        self.assertIn('applyWorkspacePayload(key, await request())', SCRIPT)
        self.assertIn('markWorkspaceModulesDirty("news", "weekly", "performance")', SCRIPT)
        self.assertIn('renderWorkspaceModule(target)', SCRIPT)
        self.assertNotIn('await Promise.allSettled(activeDefinitions.map', SCRIPT)
        app_script = (ROOT / "web" / "static" / "app.js").read_text(encoding="utf-8")
        self.assertIn('event.detail?.tab === "ai"', app_script)
        self.assertIn('function ensureAiWorkspaceData()', app_script)
        self.assertIn('Promise.allSettled([', app_script)

    def test_alert_and_log_surfaces_export_all_operational_report_periods(self):
        for label, value in (("日报", "daily"), ("周报", "weekly"), ("月报", "monthly"), ("年报", "annual")):
            self.assertIn(f'<option value="{value}">{label}</option>', INDEX)
            self.assertIn(f'<option value="{value}">{label}</option>', SCRIPT)
        self.assertIn('id="downloadLogReportButton"', INDEX)
        self.assertIn('/api/log-report.pdf?period=', (ROOT / "web" / "static" / "app.js").read_text(encoding="utf-8"))
        self.assertIn('data-download-alert-report', SCRIPT)
        self.assertIn('/api/alert-report.pdf?period=', SCRIPT)
        self.assertIn('.operational-report-control', STYLE)

    def test_navigation_is_linkable_responsive_and_keyboard_accessible(self):
        responsive_style = (
            ROOT / "web" / "static" / "responsive-layout-hardening.css"
        ).read_text(encoding="utf-8")

        self.assertIn('params.get("workspace")', SCRIPT)
        self.assertIn('"ArrowLeft", "ArrowRight", "ArrowUp", "ArrowDown", "Home", "End"', SCRIPT)
        self.assertIn("@media (max-width: 560px)", STYLE)
        self.assertIn("overflow-x: auto", STYLE)
        self.assertIn('/static/news-review-sheet.css?v=6', INDEX)
        self.assertRegex(INDEX, r'/static/workspace-tabs\.css\?v=\d+')
        self.assertRegex(INDEX, r'/static/workspace-tabs\.js\?v=\d+')
        self.assertIn("width: min(calc(100% - 28px),1600px)", STYLE)
        self.assertIn("@media (max-width: 1490px)", STYLE)
        self.assertIn("aspect-ratio: 960 / 390", STYLE)
        self.assertIn("backdrop-filter: blur(22px) saturate(138%)", STYLE)
        self.assertIn("border-radius: 18px", STYLE)
        self.assertIn(".workspace-tab.is-active::after", STYLE)
        self.assertIn("prefers-reduced-motion: reduce", STYLE)
        self.assertIn("workspace-motion-stage", STYLE)
        self.assertIn("workspace-signal-arrival", STYLE)
        self.assertIn("animation: workspace-alert-breathe 1.55s ease-in-out infinite", STYLE)
        self.assertNotIn(".workspace-tab.has-unread-signal:not(.is-active)", STYLE)
        self.assertIn("0%,100% { border-color: transparent;", STYLE)
        self.assertIn("clearWorkspaceSignal(target);", SCRIPT)
        self.assertIn('window.CMHKMotion = { announce: announceWorkspaceEvent }', SCRIPT)
        self.assertIn('event.data?.type !== "cmhk-workspace-motion"', SCRIPT)
        self.assertIn("calc(100vh / 1044px)", responsive_style)
        self.assertIn("calc((100vh - 8px) / 1096px)", responsive_style)
        self.assertIn("height: 154px; gap: 3px; padding: 29px 12px 9px", STYLE)
        self.assertIn('refreshFaultData({ quiet: true })', SCRIPT)
        self.assertNotIn("workspace-running-dot", STYLE)
        self.assertIn('class="workspace-nav-icon"', INDEX)
        self.assertIn('class="workspace-nav-icon-arrow"', INDEX)
        self.assertNotIn("workspace-collapse-chevron-float", STYLE)
        self.assertNotIn("clip-path: polygon(13% 5%", STYLE)
        self.assertIn("Counter that", STYLE)
        self.assertIn("calc(236px / var(--fit-scale))", STYLE)
        self.assertIn("scale(calc(1 / var(--fit-scale)))", STYLE)
        self.assertIn("transform: translateY(-105%);", STYLE)
        self.assertIn(".dashboard-page.workspace-ai-active .workspace-layout { height: 100dvh; }", STYLE)
        self.assertIn('setWorkspaceNavCollapsed?.(true, { fromRect: navTransitionStart });', SCRIPT)
        self.assertIn(".workspace-nav-icon-arrow,", STYLE)
        self.assertIn('window.matchMedia("(prefers-reduced-motion: reduce)")', SCRIPT)
        self.assertIn('panel.classList.add("is-panel-entering")', SCRIPT)
        self.assertIn('motionPreference.matches ? "auto" : "smooth"', SCRIPT)
        self.assertIn("@keyframes workspace-panel-enter", STYLE)
        self.assertIn("@keyframes workspace-dialog-enter", STYLE)
        self.assertIn("@keyframes workspace-content-replace", STYLE)
        self.assertIn("@keyframes organization-menu-enter", ORGANIZATION_STYLE)
        self.assertIn("@keyframes news-review-workspace-enter", NEWS_REVIEW_STYLE)
        self.assertIn("@keyframes news-review-filter-enter", NEWS_REVIEW_STYLE)
        self.assertIn('layout.classList.add("is-nav-positioning")', SCRIPT)
        self.assertIn("--workspace-nav-motion-x", SCRIPT)
        self.assertIn("transition: transform .52s cubic-bezier(.22,1,.36,1)", STYLE)
        self.assertIn('button.setAttribute("aria-busy", "true")', SCRIPT)
        self.assertIn("Boolean(state.status?.tasks?.hasRunning)", SCRIPT)
        self.assertIn('runningIndicator.dataset.indicatorRunning = "true"', SCRIPT)
        self.assertIn('["indicatorRunning", "indicatorReport", "indicatorSignal"]', SCRIPT)
        self.assertIn("Unified floating workspace surfaces", STYLE)
        self.assertIn("--workspace-surface", STYLE)
        for asset in (
            "workspace-bg-intelligence-v1.png",
            "workspace-bg-content-v1.png",
            "workspace-bg-operations-v1.png",
        ):
            self.assertIn(asset, STYLE)
            self.assertTrue((ROOT / "web" / "static" / "assets" / asset).exists())
        self.assertIn(":not(.workspace-ai-active) .workspace-panel", STYLE)
        self.assertIn("background-color: rgba(7, 29, 41, .56) !important", STYLE)
        self.assertIn("backdrop-filter: blur(7px) saturate(120%)", STYLE)
        self.assertIn('/static/subscription-admin.css?v=25', (ROOT / "web" / "static" / "subscription-admin.html").read_text(encoding="utf-8"))

    def test_subscription_management_uses_server_and_feishu_delivery(self):
        self.assertIn('id="workspace-tab-subscriptions"', INDEX)
        self.assertIn('/static/subscription-admin.html?v=15', INDEX)
        self.assertNotIn('class="subtitle"', SUBSCRIPTION_SCRIPT)
        self.assertIn('fetch("/api/subscriptions"', SUBSCRIPTION_SCRIPT)
        self.assertIn('action: "publish"', SUBSCRIPTION_SCRIPT)
        self.assertIn('action: "pushLatest"', SUBSCRIPTION_SCRIPT)
        self.assertIn('announceDeliveredMessage(payload.action, evidence)', SUBSCRIPTION_SCRIPT)
        self.assertIn("strategic_news_schedule", SUBSCRIPTION_SCRIPT)
        self.assertIn("战略新闻定时推送", SUBSCRIPTION_SCRIPT)
        self.assertIn("07:30 / 14:00", SUBSCRIPTION_SCRIPT)
        self.assertIn("推送记录", SUBSCRIPTION_SCRIPT)
        self.assertIn("confirmBulk", SUBSCRIPTION_SCRIPT)
        self.assertIn("@media (max-width: 560px)", SUBSCRIPTION_STYLE)
        self.assertIn("border-radius: 14px", SUBSCRIPTION_STYLE)
        self.assertIn("workspace-bg-content-v1.png", SUBSCRIPTION_STYLE)
        self.assertNotIn("订阅服务 UI DEMO", SCRIPT)
        self.assertNotIn('localStorage.setItem("cmhk-weekly-subscription"', SCRIPT)

    def test_company_data_failure_state_tolerates_optional_stats_host(self):
        script = (ROOT / "web" / "static" / "company-data.js").read_text(
            encoding="utf-8"
        )

        self.assertIn(
            'if (els.stats) els.stats.innerHTML = `<span>加载失败</span>`;',
            script,
        )

    def test_external_links_are_protocol_checked_and_api_failures_are_isolated(self):
        self.assertIn('const safeUrl =', SCRIPT)
        self.assertIn('["http:", "https:"]', SCRIPT)
        self.assertIn("Promise.allSettled", SCRIPT)
        self.assertIn("renderLoadError", SCRIPT)

    def test_existing_ai_log_and_report_surfaces_are_moved_into_tabs(self):
        self.assertIn('document.querySelector("#chatModal")', SCRIPT)
        self.assertIn('document.querySelector("#logModal")', SCRIPT)
        self.assertIn('document.querySelector(weekly ? "#weeklyOutputBlock"', SCRIPT)
        self.assertIn("appendChild(chat)", SCRIPT)
        self.assertIn("appendChild(log)", SCRIPT)
        self.assertIn("appendChild(outputBlock)", SCRIPT)
        self.assertIn('id="workspaceNavCollapse"', INDEX)
        self.assertIn("is-nav-collapsed", STYLE)
        self.assertIn('class="workspace-monitoring-frame"', INDEX)
        self.assertIn("CMHK战略竞对中心", INDEX)
        self.assertIn("executive-dashboard-demo.html?embedded=1&amp;v=3", INDEX)

    def test_report_modules_open_pdf_previews_and_keep_word_downloads_without_top_kpi_strip(self):
        self.assertNotIn("docx-preview", INDEX)
        self.assertIn("reportPreviewPdfUrl", SCRIPT)
        self.assertIn("正在读取 PDF 版式预览", SCRIPT)
        self.assertIn("data-report-preview-expand", SCRIPT)
        self.assertIn("workspaceReportSide-${kind}", SCRIPT)
        self.assertIn("showReportPreview(row.dataset.path)", SCRIPT)
        render_reports = SCRIPT[SCRIPT.index("function renderReports"):SCRIPT.index("function reportPreviewPlaceholder")]
        self.assertNotIn("workspace-kpi-strip", render_reports)
        self.assertIn(".report-preview.is-maximized", STYLE)
        self.assertIn("height: 100dvh", STYLE)
        self.assertIn(".workspace-content { height: 100%;", STYLE)
        self.assertIn("transform: none !important", STYLE)
        self.assertIn("state.previewRequest.weekly += 1", SCRIPT)
        self.assertIn("state.previewRequest.performance += 1", SCRIPT)
        self.assertIn("border-radius: 10px", STYLE)

    def test_existing_feishu_review_sheet_is_reused_as_a_workspace_tab(self):
        self.assertIn('id="workspace-tab-review"', INDEX)
        self.assertIn("新闻审核", INDEX)
        self.assertIn('document.querySelector("#newsReviewWorkspace")', SCRIPT)
        self.assertIn('appendChild(review)', SCRIPT)

    def test_navigation_groups_and_renames_business_modules(self):
        intelligence = INDEX[INDEX.index('id="workspace-group-intelligence"'):INDEX.index('id="workspace-group-products"')]
        products = INDEX[INDEX.index('id="workspace-group-products"'):INDEX.index('id="workspace-group-assistant"')]
        assistant = INDEX[INDEX.index('id="workspace-group-assistant"'):INDEX.index('id="workspace-group-tools"')]
        operations = INDEX[INDEX.index('id="workspace-group-tools"'):INDEX.index('id="workspace-panel-dashboard"')]
        self.assertIn("情报采集与研判", intelligence)
        self.assertIn("新闻采集", intelligence)
        self.assertIn("新闻审核", intelligence)
        self.assertIn("竞对分析", intelligence)
        self.assertNotIn("新闻获取与推送", intelligence)
        self.assertNotIn("新闻过滤与审核", intelligence)
        self.assertIn("报告与触达", products)
        self.assertLess(products.index("战略周报"), products.index("业绩摘要"))
        self.assertLess(products.index("业绩摘要"), products.index("订阅与推送"))
        self.assertNotIn("竞对分析", products)
        self.assertIn("智能工具", assistant)
        self.assertIn("小竞AI", assistant)
        self.assertNotIn("小竞AI", products)
        self.assertNotIn("AI问数", INDEX)
        self.assertNotIn("小竞AI", operations)
        self.assertIn("项目系统架构", operations)
        self.assertIn('data-workspace-tab="architecture" data-workspace-tab-hidden hidden', operations)
        self.assertIn('tab.hasAttribute("data-workspace-tab-hidden")', SCRIPT)

    def test_navigation_uses_semantic_icons_instead_of_numeric_badges(self):
        navigation = INDEX[INDEX.index('id="workspace-group-overview"'):INDEX.index('id="workspace-panel-dashboard"')]
        self.assertEqual(15, navigation.count('class="workspace-tab-icon"'))
        self.assertEqual(15, navigation.count('class="workspace-tab-icon" aria-hidden="true"'))
        self.assertNotIn('workspace-tab-index', navigation)
        for badge in (">00<", ">01<", ">02<", ">03<", ">04<", ">05<", ">06<", ">07<", ">08<", ">09<", ">10<", ">11<"):
            self.assertNotIn(badge, navigation)
        self.assertIn('.workspace-tab-icon svg', STYLE)

    def test_xiaojing_navigation_uses_the_existing_product_logo(self):
        assistant = INDEX[INDEX.index('id="workspace-group-assistant"'):INDEX.index('id="workspace-group-tools"')]
        self.assertIn('class="workspace-tab-icon"', assistant)
        self.assertIn('/static/assets/logo/xiaojing-ai-logo-mark.png?v=2', assistant)
        self.assertNotIn("<svg", assistant)
        self.assertIn('#workspace-tab-ai .workspace-tab-icon img', STYLE)

    def test_fault_monitor_uses_real_incident_ledger_with_identity_bound_resolution(self):
        self.assertIn('id="workspace-tab-fault"', INDEX)
        self.assertIn("报警处置", INDEX)
        self.assertIn('fetch("/api/project-incidents?limit=500"', SCRIPT)
        self.assertIn("state.faultTotal", SCRIPT)
        self.assertIn("filtersActive ? rows.length : state.faultTotal", SCRIPT)
        self.assertIn("renderFaultMonitor", SCRIPT)
        self.assertIn('data-fault-filter="status"', SCRIPT)
        self.assertIn('data-fault-filter="kind"', SCRIPT)
        self.assertIn("data-fault-detail", SCRIPT)
        self.assertIn("报警总数", SCRIPT)
        self.assertIn("报警原因", SCRIPT)
        self.assertIn("解决原因", SCRIPT)
        self.assertIn("紧急程度", SCRIPT)
        self.assertIn("处理主体", SCRIPT)
        self.assertIn('data-fault-sort="${key}"', SCRIPT)
        self.assertIn('aria-sort="${ariaSort}"', SCRIPT)
        self.assertIn("faultSeverity", SCRIPT)
        self.assertIn("faultHandler", SCRIPT)
        self.assertIn("建议处理方法", SCRIPT)
        self.assertIn("当时的处理建议", SCRIPT)
        self.assertIn("faultSolutions", SCRIPT)
        self.assertIn('task.source === "project-monitor"', SCRIPT)
        self.assertIn('class="fault-row"', SCRIPT)
        self.assertIn('data-fault-resolve=', SCRIPT)
        self.assertIn('fetch("/api/project-incidents/resolve"', SCRIPT)
        self.assertIn('id="faultActionFeedback"', SCRIPT)
        self.assertIn("正在处理报警", SCRIPT)
        self.assertIn("处理失败，未改变报警状态", SCRIPT)
        self.assertIn("preserveFeedback: true", SCRIPT)
        self.assertNotIn('incident_status: "resolved"', SCRIPT)
        self.assertIn(".fault-row.is-resolving", STYLE)
        self.assertIn(".fault-action-feedback.is-success", STYLE)
        self.assertIn(".fault-action-feedback.is-error", STYLE)
        self.assertIn("faultHandlerAvatar", SCRIPT)
        self.assertIn('task.incident_status === "resolved"', SCRIPT)
        self.assertIn('const checked = Boolean(task.handler_name);', SCRIPT)
        self.assertIn('const closedByMonitor = task.incident_status === "resolved" && !checked;', SCRIPT)
        self.assertNotIn('Boolean(task.handler_name) || task.incident_status === "resolved"', SCRIPT)
        self.assertIn('checked || resolving || closedByMonitor || !canResolve', SCRIPT)
        self.assertIn("证据结案时间", SCRIPT)
        self.assertIn("人工修复时间", SCRIPT)
        self.assertIn("监控验证器", SCRIPT)
        self.assertIn("LLM 告警总结", SCRIPT)
        self.assertIn("LLM 结案总结", SCRIPT)
        self.assertIn("已确认信息", SCRIPT)
        self.assertIn("分析推断", SCRIPT)
        self.assertIn("结案验证证据", SCRIPT)
        self.assertIn("faultResolutionReason", SCRIPT)
        self.assertNotIn("监控机器人·自动恢复", SCRIPT)
        self.assertIn(".fault-handler-avatar.is-system", STYLE)
        self.assertIn("input:disabled:checked", STYLE)
        self.assertIn(".fault-table .fault-row", STYLE)
        self.assertNotIn("fault-summary", SCRIPT)
        self.assertNotIn("data-restart", SCRIPT)

    def test_news_and_competitor_results_keep_vertical_scrolling(self):
        self.assertIn("#workspace-panel-news .news-process-panel", STYLE)
        self.assertIn("#workspace-panel-competitor .competitor-result", STYLE)
        self.assertIn("overflow-y: auto !important", STYLE)

    def test_competitor_workbench_starts_empty_and_uses_historical_data(self):
        self.assertIn("competitor-workbench-data.json", SCRIPT)
        self.assertIn("competitor-workbench-data.json?v=2", SCRIPT)
        self.assertIn('competitorSelection: { companies: [], metric: "", years: null }', SCRIPT)
        self.assertIn('state.competitorSelection = { companies: [], metric: "", years: null }', SCRIPT)
        self.assertIn('if (companies.length < 1 || !metric || !years)', SCRIPT)
        self.assertIn('const windows = years ? [years] : [3, 5, 10, 99];', SCRIPT)
        self.assertIn("competitorHasCompleteMetric", SCRIPT)
        self.assertIn("选择竞对", SCRIPT)
        self.assertIn("选择指标", SCRIPT)
        self.assertIn("选择年限", SCRIPT)
        self.assertIn("完成上方选择后查看数据", SCRIPT)
        self.assertIn('fetch("/api/competitor-insight-stream"', SCRIPT)
        self.assertNotIn('fetch("/api/competitor-insight"', SCRIPT)
        self.assertNotIn("requestLegacyCompetitorInsight", SCRIPT)
        self.assertIn("buildCompetitorChart", SCRIPT)
        self.assertIn("buildCompetitorBarChart", SCRIPT)
        self.assertIn('chartType === "bar" || chartType === "combo"', SCRIPT)
        self.assertIn("competitorDefaultChartType", SCRIPT)
        self.assertIn('data-competitor-chart-toggle', SCRIPT)
        self.assertIn("bindCompetitorChartTypeToggle", SCRIPT)
        self.assertIn("state.competitorChartTypes[chartKey] = chartType", SCRIPT)
        self.assertIn("current.replaceWith(template.content.firstElementChild)", SCRIPT)
        self.assertIn("切换为柱状图", SCRIPT)
        self.assertIn("切换为折线图", SCRIPT)
        self.assertIn("切换为柱线组合图", SCRIPT)
        self.assertIn('const types = ["bar", "line", "combo"]', SCRIPT)
        self.assertIn('data-next-chart-type="${nextType}"', SCRIPT)
        self.assertIn('data-chart-type="${chartType}"', SCRIPT)
        self.assertIn(".competitor-chart-type-toggle", STYLE)
        self.assertIn(".competitor-chart-bar", STYLE)
        self.assertIn(".competitor-chart-combo-series", STYLE)
        self.assertIn("competitor-result-header", SCRIPT)
        self.assertNotIn("<span>战略指标</span>", SCRIPT)
        self.assertIn("buildCompetitorCoreSummary", SCRIPT)
        self.assertIn("data-competitor-core-summary", SCRIPT)
        self.assertIn("parseCompetitorStrategicIndicator", SCRIPT)
        self.assertIn("parseCompetitorStrategicSignal", SCRIPT)
        self.assertIn("event.strategicHighlights", SCRIPT)
        self.assertIn("renderCompetitorStrategicIndicatorCopy", SCRIPT)
        self.assertIn('replace(/[。．.]+$/, "")', SCRIPT)
        self.assertIn(".competitor-core-summary strong mark", STYLE)
        self.assertIn("data:image/svg+xml", STYLE)
        self.assertIn("background-size: 100% .56em", STYLE)
        self.assertIn("event.strategicIndicator", SCRIPT)
        self.assertNotIn("AI 正在提炼一句话战略判断", SCRIPT)
        self.assertIn("competitorCoincidentGroups", SCRIPT)
        self.assertIn("竞争焦点不在基站数量差异", SCRIPT)
        self.assertIn("共享网络的运营效率和业务转化能力", SCRIPT)
        self.assertIn("已选 ${selection.companies.length} 家", SCRIPT)
        self.assertIn(".competitor-core-summary", STYLE)
        self.assertIn("span.is-coincident em", STYLE)
        self.assertNotIn("多年趋势对比", SCRIPT)
        self.assertIn("查看数据明细、缺口理由与官方来源", SCRIPT)
        self.assertIn("function competitorSourceLinks", SCRIPT)
        self.assertIn("...(cell.sources || [])", SCRIPT)
        self.assertIn(': "官方来源";', SCRIPT)
        self.assertIn('"已复核来源",', SCRIPT)
        self.assertNotIn("gap?.reviewedSources?.[0]", SCRIPT)
        self.assertIn("相关口径：", SCRIPT)
        self.assertIn("relatedPublicValue", SCRIPT)
        self.assertIn("AI 竞争洞察", SCRIPT)
        self.assertIn("buildCompetitorFallbackInsight", SCRIPT)
        self.assertIn('card.classList.remove("is-loading", "is-streaming")', SCRIPT)
        self.assertNotIn("内网 AI 正在等待安全加载", SCRIPT)
        self.assertIn('"RETRY"', SCRIPT)
        self.assertIn('"AI STREAM"', SCRIPT)
        self.assertIn("renderCompetitorInsightDraft", SCRIPT)
        self.assertNotIn("内网 AI", SCRIPT)
        self.assertIn("AI 正在流式生成", SCRIPT)
        self.assertIn("parseCompetitorInsightItems", SCRIPT)
        self.assertIn("activeLabelIndex", SCRIPT)
        self.assertIn("if (!labelled.size && !value)", SCRIPT)
        self.assertIn("filter(Boolean).slice(0, 3)", SCRIPT)
        self.assertNotIn("competitor-insight-markdown", SCRIPT)
        self.assertNotIn("competitor-insight-markdown", STYLE)
        self.assertIn("已告警并启动自动恢复", SCRIPT)
        self.assertIn("scheduleCompetitorInsightRecovery", SCRIPT)
        self.assertIn("const delays = [5, 15, 30, 60, 120, 300]", SCRIPT)
        self.assertNotIn("正在自动切换兼容通道", SCRIPT)
        self.assertIn("window.requestAnimationFrame(resolve)", SCRIPT)
        self.assertNotIn("当前显示本地数据总结", SCRIPT)
        self.assertIn("竞争格局", SCRIPT)
        self.assertIn("公司定位", SCRIPT)
        self.assertIn("业务含义", SCRIPT)
        self.assertIn("data-competitor-insight-icon", SCRIPT)
        self.assertIn('<svg viewBox="0 0 32 32" aria-hidden="true" focusable="false">', SCRIPT)
        self.assertIn(".competitor-insight-identity i svg", STYLE)
        self.assertIn("competitor-insight-star-twinkle", STYLE)
        self.assertIn("svg path:last-child { animation-delay: .42s; }", STYLE)
        self.assertNotIn("@keyframes competitor-insight-pulse", STYLE)
        self.assertNotIn("/static/assets/ai-insight-sparkle.png", SCRIPT)

        self.assertIn('setCompetitorInsightStatus(card, status || (isAi ? ""', SCRIPT)
        self.assertNotIn("内网 AI 已完成真实生成", SCRIPT)
        self.assertNotIn("AI未生成：", SCRIPT)
        self.assertIn("font-size: 14px", STYLE)
        self.assertNotIn("competitor-insight-facts", SCRIPT)
        self.assertNotIn("最新共同年差距", SCRIPT)
        self.assertNotIn("数据口径</span>", SCRIPT)
        self.assertIn('["~", "approx", "≈"]', SCRIPT)
        self.assertIn("competitor-insight-shimmer", STYLE)
        self.assertIn("competitor-strategic-caret", STYLE)
        self.assertIn("competitor-insight-paragraph-in", STYLE)
        self.assertIn("overflow-y: auto", STYLE)
        self.assertIn("scrollbar-gutter: stable", STYLE)
        self.assertIn("competitor-matrix", STYLE)
        self.assertIn("competitor-chart-series", STYLE)
        self.assertIn("competitorInsightController?.abort()", SCRIPT)
        self.assertIn('error.name === "AbortError"', SCRIPT)
        self.assertIn("所选组合尚无审计记录", SCRIPT)
        self.assertIn("整个年份窗口均有披露值", SCRIPT)
        self.assertIn("visibleCompetitorIds", SCRIPT)
        self.assertIn("competitorHasCompleteMetric", SCRIPT)
        self.assertIn('classList.add("is-disappearing")', SCRIPT)
        self.assertNotIn("animateCompetitorOptionParticles", SCRIPT)
        self.assertNotIn("competitor-particle-layer", STYLE)
        self.assertIn("--option-order", SCRIPT)
        self.assertIn("transition-delay: calc(var(--option-order,0) * 12ms)", STYLE)
        self.assertIn("flex-wrap: wrap; align-items: flex-start; gap: 5px", STYLE)
        self.assertIn("label.is-disappearing > b { max-width: none; white-space: nowrap; }", STYLE)
        self.assertIn("competitor-option-appear", STYLE)
        self.assertIn("所选组合的计量单位不一致", SCRIPT)
        self.assertNotIn("依次选择竞对、同单位指标和共同披露年", SCRIPT)
        self.assertNotIn("正在汇总 ${runs.length} 次真实新闻任务", SCRIPT)
        self.assertIn('id="newsReviewSyncText" role="status" hidden', INDEX)
        self.assertNotIn("competitor-knowledge-layer", SCRIPT)
        self.assertIn("本地运营商知识库", SCRIPT)
        self.assertIn("全球重点运营商知识库", SCRIPT)
        self.assertIn("competitor-result-overview", STYLE)
        self.assertNotIn("LOCAL DATA", SCRIPT)
        self.assertNotIn("fallbackInsight.insights", SCRIPT)

    def test_competitor_selector_text_is_slightly_enlarged(self):
        self.assertIn(".competitor-steps legend {", STYLE)
        self.assertIn("font-size: 12px; font-weight: 700", STYLE)
        self.assertIn("legend small { float: right; color: #6f929f; font-size: 9px", STYLE)
        self.assertIn("label > b,.competitor-year-options span", STYLE)
        self.assertIn("font-size: 10px; font-weight: 600", STYLE)
        self.assertIn(".competitor-select select", STYLE)
        self.assertIn("font-size: 11px;", STYLE)

    def test_review_sheet_uses_cached_snapshot_and_inline_escape_is_safe(self):
        review_script = (ROOT / "web" / "static" / "news-review-sheet.js").read_text(encoding="utf-8")
        self.assertIn("cmhk-news-review-snapshot-v3", review_script)
        self.assertIn('workspace.classList.contains("workspace-inline-review")', review_script)
        self.assertIn("NEWS_REVIEW_SNAPSHOT_CACHE_KEY", SCRIPT)
        self.assertIn('snapshotMode: "cached"', SCRIPT)
        self.assertIn("sessionStorage.setItem(NEWS_REVIEW_SNAPSHOT_CACHE_KEY", SCRIPT)
        self.assertIn("最近完整快照", SCRIPT)

    def test_news_module_replays_the_full_ai_review_pipeline_by_single_date(self):
        self.assertIn('fetch("/api/crawl-runs?taskKind=strategic-news&limit=365")', SCRIPT)
        self.assertIn("/api/crawl-run-log?id=", SCRIPT)
        self.assertIn("data-news-date-select", SCRIPT)
        self.assertIn('type="date" data-news-date-select', SCRIPT)
        self.assertIn('newsDatePicker.showPicker()', SCRIPT)
        self.assertIn("当天暂无新闻采集运行归档", SCRIPT)
        self.assertNotIn("<select data-news-date-select", SCRIPT)
        self.assertNotIn("data-news-run-option", SCRIPT)
        self.assertNotIn("data-news-date-option", SCRIPT)
        self.assertIn("newsSelectedDate", SCRIPT)
        self.assertIn("newsSelectedRunIds", SCRIPT)
        self.assertIn("aggregateNewsStages", SCRIPT)
        self.assertIn("openActualNewsLineageDetail", SCRIPT)
        self.assertIn("当天实际处理轨迹", SCRIPT)
        self.assertIn("当天真实新增新闻", SCRIPT)
        self.assertIn("AI 纳入理由", SCRIPT)
        self.assertIn("aiReviewItems", SCRIPT)
        self.assertIn("dedupeItems", SCRIPT)
        self.assertIn("当天处理对象明细", SCRIPT)
        self.assertIn("AI 排除原因", SCRIPT)
        self.assertIn("排除代码", SCRIPT)
        self.assertIn("detailedRecordsForNode", SCRIPT)
        self.assertIn('params.get("newsDate")', SCRIPT)
        self.assertNotIn('name="news-archive-filter"', SCRIPT)
        for stage in ("线索发现", "确定性门禁", "AI 语义审核", "历史语义去重", "飞书写入回读", "群组推送"):
            self.assertIn(stage, SCRIPT)
        self.assertNotIn("最新战略快讯", SCRIPT)
        self.assertIn("@keyframes news-signal", STYLE)
        self.assertIn("prefers-reduced-motion", STYLE)

    def test_news_module_exposes_clickable_live_lineage_with_detailed_dialog(self):
        for label in (
            "07:30 / 14:00 定时启动器",
            "按关键词搜索公开网页",
            "AI 新闻相关性审核",
            "历史新闻重复检查",
            "新增战略新闻保存与归档",
            "AI 滚动栏与周报初筛",
            "纳入滚动栏",
            "纳入周报",
        ):
            self.assertIn(label, SCRIPT)
        self.assertIn("data-news-lineage-node", SCRIPT)
        self.assertIn("点击查看整理详情", SCRIPT)
        self.assertIn("syncNewsLineageEdges", SCRIPT)
        self.assertNotIn("setPointerCapture", SCRIPT)
        self.assertNotIn("localStorage.setItem(storageKey", SCRIPT)
        self.assertIn("当天结果摘要", SCRIPT)
        self.assertIn("上下游", SCRIPT)
        self.assertIn("当天归档摘要", SCRIPT)
        self.assertIn("当天具体内容", SCRIPT)
        self.assertIn("错误定位与完整明细", SCRIPT)
        self.assertIn("newsRunErrors", SCRIPT)
        self.assertIn("查看完整错误原文", SCRIPT)
        self.assertIn("本节点实际输入、动作与输出", SCRIPT)
        self.assertIn("实际对象预览", SCRIPT)
        self.assertIn("newsLineageFirstScreenModel", SCRIPT)
        self.assertIn("renderNewsLineageFirstScreen", SCRIPT)
        self.assertIn("页面不会编造链接、关键词或数据", SCRIPT)
        self.assertIn(".news-lineage-io-flow", STYLE)
        self.assertIn(".news-lineage-first-preview", STYLE)

    def test_news_selection_summary_distinguishes_verified_and_new_writes(self):
        self.assertIn("function selectionRunBatchKey(run)", SCRIPT)
        self.assertIn("function selectionRunBusinessDate(run)", SCRIPT)
        self.assertIn("function verifiedSelectionRun(run)", SCRIPT)
        self.assertIn("function selectionAttemptRunsForDate(date)", SCRIPT)
        self.assertIn("function authoritativeSelectionRunsForDate(date)", SCRIPT)
        self.assertIn("selectionRunBusinessDate(run) === date", SCRIPT)
        self.assertIn("runVerified && !currentVerified", SCRIPT)
        self.assertIn("current?.operational_summary?.reused === true", SCRIPT)
        self.assertIn("const selectionAttemptRuns = selectionAttemptRunsForDate(selectedDate)", SCRIPT)
        self.assertIn("const selectionRuns = authoritativeSelectionRunsForDate(selectedDate)", SCRIPT)
        self.assertIn("成功回读覆盖同批失败尝试", SCRIPT)
        self.assertIn("运行尝试 ${number(selectionAttemptRuns.length)} 次", SCRIPT)
        self.assertIn("evidence: selectionAttemptRuns.map", SCRIPT)
        self.assertIn("summary.verifiedCells", SCRIPT)
        self.assertIn("summary.newCells", SCRIPT)
        self.assertIn("summary.alreadyAppliedCells", SCRIPT)
        self.assertIn("飞书机器人验证", SCRIPT)
        self.assertIn("本次新写", SCRIPT)
        self.assertIn("写前已有", SCRIPT)
        self.assertNotIn("飞书机器人写入 ${number(selectionSummary.cells)} 格", SCRIPT)
        self.assertIn("本节点无直接错误；异常来自关联运行的其他环节", SCRIPT)
        self.assertIn(".news-lineage-error-list", STYLE)
        self.assertIn("news-lineage-pulse", STYLE)
        self.assertIn("@keyframes news-lineage-flow", STYLE)
        self.assertIn(".news-lineage-dialog-summary", STYLE)
        self.assertIn(".news-stage-dialog.news-lineage-dialog", STYLE)
        self.assertIn("--news-lineage-edge-space: clamp(28px,3.2vw,72px)", STYLE)
        self.assertIn("padding: 14px var(--news-lineage-edge-space) 22px", STYLE)
        self.assertIn("scrollbar-gutter: stable both-edges", STYLE)
        self.assertIn("--news-lineage-edge-space: 10px", STYLE)
        self.assertIn("height: 100dvh", STYLE)
        self.assertIn(".news-lineage-detail-items::-webkit-scrollbar", STYLE)
        self.assertIn("overflow-y: scroll", STYLE)
        self.assertIn("is-item-details", SCRIPT)
        self.assertIn("grid-auto-rows: max-content", STYLE)
        self.assertIn("actualEventsForNode", SCRIPT)
        self.assertIn("当天原始处理记录", SCRIPT)
        self.assertIn("lineageRunsForNode", SCRIPT)
        self.assertIn('fetch("/api/crawl-runs?limit=500"', SCRIPT)
        self.assertIn("当天未留下该节点的逐步处理记录", SCRIPT)
        self.assertNotIn("完整处理流程", SCRIPT)
        self.assertNotIn("规则／门禁", SCRIPT)
        self.assertNotIn("lineageProcessStep", SCRIPT)
        self.assertNotIn("processSteps = processByNode", SCRIPT)
        self.assertIn(".news-lineage-process-steps", STYLE)
        self.assertIn('fetch("/api/news-review-sheet"', SCRIPT)
        self.assertIn('valueAt(row, "检索日期")', SCRIPT)
        self.assertIn('row.rollingStatus === "接受"', SCRIPT)
        self.assertIn('row.weeklyStatus === "接受"', SCRIPT)
        self.assertIn("当天选用明细", SCRIPT)
        self.assertIn(".news-lineage.is-global .news-lineage-node.is-result", STYLE)

    def test_news_module_maps_all_periodic_crawlers_into_four_database_updates(self):
        self.assertIn('fetch("/api/scheduler-overview"', SCRIPT)
        self.assertIn('fetch("/api/executive-intelligence"', SCRIPT)
        for label in (
            "07:30 / 14:00 定时启动器",
            "按关键词搜索公开网页",
            "AI 新闻相关性审核",
            "历史新闻重复检查",
            "新增战略新闻保存与归档",
            "01:00 四库缺口链接搜索",
            "03:00 两类链接网页抓取",
            "03:00 字段提取与候选数据生成",
            "Agent 数据证据逐条审核",
            "本地运营商",
            "国际运营商",
            "内地运营商",
            "全球云厂商",
            "AI 战略洞察生成与 UI 发布",
        ):
            self.assertIn(label, SCRIPT)
        self.assertIn("expectedFocusInsightCount + expectedDiscoveryInsightCount", SCRIPT)
        self.assertIn("focusInsightCount + discoveryInsightCount", SCRIPT)
        self.assertIn("顶部跨库研判 ${number(discoveryInsightCount)} / ${number(expectedDiscoveryInsightCount)}", SCRIPT)
        self.assertIn('fetch("/api/crawl-runs?limit=500"', SCRIPT)
        self.assertIn("function mainRunForDate(date)", SCRIPT)
        self.assertIn("function authoritativeSourceDiscoveryRunForDate(date)", SCRIPT)
        self.assertIn('String(run.started_at_hkt || "").slice(11, 13) === "01"', SCRIPT)
        self.assertIn("run.operational_summary?.feishu_detail_log?.readback_verified === true", SCRIPT)
        self.assertIn("runCompletedDate(run) === date", SCRIPT)
        self.assertIn("function linkedParentRunId(run)", SCRIPT)
        self.assertIn('linkedParentRunId(run) === mainRun.crawl_run_id', SCRIPT)
        self.assertIn('workspace-tabs.css?v=160', INDEX)
        self.assertIn('workspace-tabs.js?v=186', INDEX)
        self.assertIn('selectedTab.scrollIntoView({ block: "nearest", inline: "center"', SCRIPT)
        self.assertIn('workspace-tabs.css?v=160', INDEX)
        self.assertIn('synchronizeWorkspaceLayoutScale(wasDashboard !== targetIsDashboard)', SCRIPT)
        self.assertIn('is-workspace-layout-switching', SCRIPT)
        self.assertIn('.dashboard-page.is-workspace-layout-switching .workspace-tabs', STYLE)
        self.assertIn('.dashboard-page.is-workspace-layout-switching .workspace-layout { transition: none; }', STYLE)
        self.assertIn("const mainRun = mainRunForDate(date)", SCRIPT)
        self.assertIn("跨日任务", SCRIPT)
        self.assertIn("linkedParentRunId(run) === mainRun.crawl_run_id", SCRIPT)
        self.assertIn("actualEventsForNode", SCRIPT)
        self.assertIn("AGENT_TRACE=", SCRIPT)
        self.assertIn("当天实际处理轨迹", SCRIPT)
        self.assertIn("不展示通用逻辑原则", SCRIPT)
        self.assertNotIn("data-news-lineage-mode", SCRIPT)
        self.assertNotIn("本轮线索", SCRIPT)
        self.assertIn("canvasSize: [1850, 755]", SCRIPT)
        self.assertIn('key: "news-selection-agent", label: "AI 滚动栏与周报初筛"', SCRIPT)
        self.assertIn("const nodePurposes = {", SCRIPT)
        self.assertIn('main: "合并飞书固定链接和B2的01:00待追证链接；抓取网页并继续打开公司IR、财报和监管披露原文，本节点只负责抓取"', SCRIPT)
        self.assertIn('"fact-extract": "读取C1a已抓取的网页正文，提取主体、指标、期间、数值、单位和来源，形成候选数据并交给C2审核"', SCRIPT)
        self.assertIn('agent: "同时接收C1a抓取的官方原文和C1b形成的候选数据', SCRIPT)
        self.assertIn('${node.primary ? " is-primary" : ""}', SCRIPT)
        self.assertIn('证据审核核心', SCRIPT)
        self.assertNotIn('<p>作用：${esc(node.purpose || "未说明")}</p>', SCRIPT)
        self.assertIn('const mainUnit = "次网址抓取"', SCRIPT)
        self.assertIn('fixedSourceSummary', SCRIPT)
        self.assertIn('/api/fixed-source-summary', SCRIPT)
        self.assertIn('id="newsLineagePurposeTooltip" role="tooltip" hidden', SCRIPT)
        self.assertIn('role="tooltip" hidden><span></span></div>', SCRIPT)
        self.assertNotIn('节点具体作用</small>', SCRIPT)
        self.assertNotIn('点击节点可查看当天真实处理记录</em>', SCRIPT)
        self.assertIn('data-news-lineage-purpose="${esc(node.purpose || "未说明")}"', SCRIPT)
        self.assertIn('canvas.addEventListener("pointerover"', SCRIPT)
        self.assertIn('canvas.addEventListener("focusin"', SCRIPT)
        self.assertIn('.news-lineage-purpose-tooltip[hidden]', STYLE)
        self.assertIn('`周报新闻 ${number(selectionSummary.weeklyAccepted)} 条`', SCRIPT)
        self.assertIn('`滚动栏新闻 ${number(selectionSummary.appAccepted)} 条`', SCRIPT)
        self.assertIn('appMachineRows', SCRIPT)
        self.assertIn('appHumanRows', SCRIPT)
        self.assertIn('weeklyMachineRows', SCRIPT)
        self.assertIn('weeklyHumanRows', SCRIPT)
        self.assertIn("机器只按已验证的新闻自动初筛操作者统计", SCRIPT)
        self.assertIn('.news-lineage-node.is-dual-metric > strong', STYLE)
        self.assertIn('["news-output", "news-selection-agent", "新增新闻初筛", "cyan"]', SCRIPT)
        self.assertIn("机器人身份纠正|当天范围门禁|机器人分批写入", SCRIPT)
        self.assertIn("detail.newsSelectionItems", SCRIPT)
        self.assertIn("当天新闻自动初筛明细", SCRIPT)
        self.assertIn('label: "审核通过数据写入四库"', SCRIPT)
        self.assertNotIn('label: "官方原文复核 / 数据库入库"', SCRIPT)
        self.assertNotIn('label: "AI洞察与业务应用"', SCRIPT)
        self.assertIn('unit: "条审核通过数据写入四库"', SCRIPT)
        self.assertIn('unit: "个主体发布到 UI"', SCRIPT)
        self.assertIn('hasCompanyAgentProgress ? "家公司数据证据已记录"', SCRIPT)
        self.assertIn(': "条候选数据审核通过", note:', SCRIPT)
        self.assertIn('unit: "项数据洞察发布到 UI"', SCRIPT)
        self.assertIn("executiveDomainFactsForDate", SCRIPT)
        self.assertIn("当天数据库入库与数值变化", SCRIPT)
        self.assertIn("当天UI重新发布与数值变化", SCRIPT)
        self.assertIn("重新发布 · 数值未变", SCRIPT)
        self.assertIn("重新发布 ${number(uiItemCount)} 个主体 · 数据指标变化 ${numericChangeText}", SCRIPT)
        self.assertIn("与更新前相同字段逐项比较后，未发现结构化数值变化", SCRIPT)
        self.assertIn('status: hasNumericChange ? "value-changed" : "updated"', SCRIPT)
        self.assertIn("change.old_value", SCRIPT)
        self.assertIn("change.new_value", SCRIPT)
        self.assertIn("页面内容指纹变化", SCRIPT)
        self.assertIn("这些均不计作数值变化", SCRIPT)
        self.assertIn(".news-lineage-detail-items > article.is-decision-value-changed", STYLE)
        self.assertNotIn("数据变化 ${number(sourceChanged)} 项", SCRIPT)
        self.assertNotIn('unit: intelligenceRun.crawl_run_id ? "项更新到UI"', SCRIPT)
        self.assertIn("(domain.entities || []).map((item) => uiRecord(domain, item))", SCRIPT)
        self.assertIn("(domain.focuses || []).map((focus) => insightRecord(domain, focus))", SCRIPT)
        self.assertIn("成功来源中：页面内容指纹变化", SCRIPT)
        self.assertNotIn('value: intelligenceRun.crawl_run_id ? "已更新"', SCRIPT)
        self.assertIn('label: "01:00 四库缺口链接搜索"', SCRIPT)
        self.assertIn('if (nodeKey === "news-db-signal")', SCRIPT)
        self.assertIn("当天具体线索与官方追证入口", SCRIPT)
        self.assertIn("具体线索 ${records.length} 条", SCRIPT)
        self.assertIn('resultLabel: "待追官方原文"', SCRIPT)
        self.assertIn("signal.official_followup_urls", SCRIPT)
        self.assertIn("只作为追证入口", SCRIPT)
        self.assertIn('${esc(record.evidenceLinkLabel || "官方地址")} ${number(index + 1)}', SCRIPT)
        self.assertIn(".news-lineage-detail-items > article.is-decision-handoff", STYLE)
        self.assertIn('if (nodeKey === "main")', SCRIPT)
        self.assertIn('["fact-extract", "agent"].includes(nodeKey)', SCRIPT)
        self.assertIn('if (nodeKey === "agent")', SCRIPT)
        self.assertIn("detail.crawlItems", SCRIPT)
        self.assertIn("detail.agentReviewItems", SCRIPT)
        self.assertIn("detail.companyAgentReports", SCRIPT)
        self.assertIn("detail.companyAgentTrace", SCRIPT)
        self.assertIn("detail.companyAgentProgress", SCRIPT)
        self.assertIn("const initialCrawlRuns = selectedNewsRuns();", SCRIPT)
        self.assertIn("loadNewsRuns(initialCrawlRuns.map((run) => run.crawl_run_id));", SCRIPT)
        self.assertIn("家公司数据证据已记录", SCRIPT)
        self.assertIn("记录值：", SCRIPT)
        self.assertIn("指标证据", SCRIPT)
        self.assertIn("公司 Agent 执行图", SCRIPT)
        self.assertIn("Lead Research Agent", SCRIPT)
        self.assertIn("41 公司 Multi-Agent 子图", SCRIPT)
        self.assertIn('not_applicable: "不适用"', SCRIPT)
        self.assertIn("公司＋指标完整性门禁", SCRIPT)
        self.assertIn("逐指标终态", SCRIPT)
        self.assertIn("report.metric_results", SCRIPT)
        self.assertIn('data-company-agent-node=', SCRIPT)
        self.assertIn('aria-expanded="false"', SCRIPT)
        self.assertIn('aria-controls=', SCRIPT)
        self.assertNotIn('data-news-lineage-node="${esc(report.company)}"', SCRIPT)
        self.assertIn(".company-agent-groups", STYLE)
        self.assertIn(".company-agent-metric-results", STYLE)
        self.assertIn(".company-agent-graph { grid-template-columns: 1fr", STYLE)
        self.assertIn("原始数据指标证据 ${number(mainRun.curation.tasks)} 条", SCRIPT)
        self.assertIn("形成并归档候选数据", SCRIPT)
        self.assertIn("当天两类链接逐行抓取明细", SCRIPT)
        self.assertIn("当天字段提取与候选数据明细", SCRIPT)
        self.assertNotIn("当天33行固定源逐行抓取明细", SCRIPT)
        self.assertIn("当天Agent逐条证据审核明细", SCRIPT)
        self.assertIn("逐条审核 ${records.length} 条 · 通过 ${included} · 拒绝 ${excluded}", SCRIPT)
        self.assertIn("核验查询：", SCRIPT)
        self.assertIn("该节点有汇总结果，但当前运行未读取到逐条归档", SCRIPT)
        self.assertIn("飞书独立子表记录查询、URL抓取、HTTP结果、入库决定与拒绝原因", SCRIPT)
        self.assertIn('"合并前一天07:30/14:00两次战略新闻任务内容作参考"', SCRIPT)
        self.assertIn('key: "previous-news", label: "前一日两轮新闻合并参考"', SCRIPT)
        self.assertIn('["previous-news", "news-db-signal", "新闻补缺", "amber"]', SCRIPT)
        self.assertIn('unit: "条待追证链接"', SCRIPT)
        self.assertIn('本节点不产出数据库数据', SCRIPT)
        self.assertIn('["news-db-signal", "main", "链接交03:00", "handoff-down"]', SCRIPT)
        self.assertIn('["main", "fact-extract", "", "handoff-down"]', SCRIPT)
        self.assertIn('["main", "agent", "官方原文", "merge"]', SCRIPT)
        self.assertIn('["fact-extract", "agent", "候选数据", "merge"]', SCRIPT)
        self.assertNotIn('["news-db-signal", "database-hub", "03:00追官方原文", "amber"]', SCRIPT)
        self.assertIn('["agent", "database-hub", "", "cyan"]', SCRIPT)
        self.assertNotIn('["agent", "database-hub", "四库分流", "cyan"]', SCRIPT)
        self.assertIn('label: "审核通过数据按主体类型写入四库并发布到 UI"', SCRIPT)
        self.assertIn('label: "A｜战略新闻智能检索线"', SCRIPT)
        self.assertIn('label: "B｜四库数据资料补缺线"', SCRIPT)
        self.assertIn('label: "C｜证据审核主链：两类链接 → 抓取与提取 → 原文＋候选数据审核 → 入库 → UI", position: [18, 410]', SCRIPT)
        self.assertNotIn('note: "仅官方原文 + 字段门禁通过才写入"', SCRIPT)
        self.assertIn('agent: [700, 500]', SCRIPT)
        self.assertIn('"database-hub": [930, 530]', SCRIPT)
        self.assertIn('"database-local": [1130, 470]', SCRIPT)
        self.assertIn('"database-international": [1295, 470]', SCRIPT)
        self.assertIn('"database-cloud": [1130, 605]', SCRIPT)
        self.assertIn('"database-mainland": [1295, 605]', SCRIPT)
        self.assertIn('insights: [1525, 535]', SCRIPT)
        self.assertIn('label: "审核通过数据按主体类型写入四库并发布到 UI", note: "四库已发布数据汇总生成右侧 AI 战略洞察", position: [1090, 430], size: [389, 315]', SCRIPT)
        self.assertIn('data-news-lineage-node="main"]::after', STYLE)
        self.assertIn('content: "抓原文"', STYLE)
        self.assertIn('content: "证据审核"', STYLE)
        self.assertIn('.news-lineage.is-global .news-lineage-node.is-database-hub { width: 144px; height: 128px; min-height: 128px;', STYLE)
        self.assertIn('.news-lineage-edge-labels { position: absolute; inset: 0; z-index: 3;', STYLE)
        self.assertIn(".news-lineage-lane-label", STYLE)
        self.assertNotIn('四库更新 · 2 × 2', SCRIPT)
        self.assertIn('group.note ? `<span>${esc(group.note)}</span>` : ""', SCRIPT)
        self.assertIn('kind === "branch"', SCRIPT)
        self.assertIn('kind === "merge"', SCRIPT)
        self.assertIn('kind === "handoff-down"', SCRIPT)
        self.assertIn('kind === "feedback-side"', SCRIPT)
        self.assertIn('const railX = target.x - 8', SCRIPT)
        self.assertIn('const railX = source.x + source.w + 8', SCRIPT)
        self.assertIn('const bend = Math.min(Math.max(20, gap * .44), gap / 2)', SCRIPT)
        self.assertIn('requestAnimationFrame(() => requestAnimationFrame(syncNewsLineageEdges))', SCRIPT)
        self.assertIn('new ResizeObserver(scheduleFit)', SCRIPT)
        self.assertIn('data-news-lineage-label', SCRIPT)
        self.assertIn('path.dataset.kind === "feedback-side" ? length * .1 : length / 2', SCRIPT)
        self.assertNotIn("<textPath", SCRIPT)
        self.assertIn(".news-lineage-edge-label", STYLE)
        self.assertIn(".news-lineage.is-global .news-lineage-node.is-compact", STYLE)
        self.assertIn("animation-name: news-lineage-flow-global", STYLE)
        self.assertIn("to { stroke-dashoffset: -104; }", STYLE)
        self.assertIn("stroke-dasharray: 3 18", STYLE)
        self.assertIn("stroke-dasharray: 26 9 5 18", STYLE)
        self.assertIn("animation-name: news-lineage-schedule-flow-global", STYLE)
        self.assertIn("animation-name: news-lineage-feedback-flow-global;", STYLE)
        self.assertIn("to { stroke-dashoffset: -116; }", STYLE)
        self.assertNotIn("news-lineage-feedback-breathe", STYLE)
        self.assertIn(".news-lineage-edge.is-feedback-side .news-lineage-pulse", STYLE)
        for variant in ("is-ai", "is-app", "is-report", "is-database-local", "is-database-international", "is-database-cloud", "is-database-mainland", "is-insight", "is-delivery"):
            self.assertIn(f".news-lineage.is-global .news-lineage-node.{variant}", STYLE)
        self.assertIn('feedbackLabel: "新增新闻归档用于下一轮历史去重"', SCRIPT)
        self.assertNotIn("历史记忆影响下一轮", SCRIPT)
        self.assertNotIn('data-news-lineage-action="zoom-out"', SCRIPT)
        self.assertNotIn('data-news-lineage-action="zoom-in"', SCRIPT)
        self.assertNotIn('key: "consumers"', SCRIPT)
        self.assertNotIn('["insights", "consumers"', SCRIPT)
        for key in ("strategic", "news-search", "news-ai", "news-dedupe", "news-output", "main", "agent", "insights"):
            self.assertIn(f'key: "{key}"', SCRIPT)
        for domain in ("local", "international", "cloud", "mainland"):
            self.assertIn(f'domainNode("{domain}"', SCRIPT)

    def test_news_lineage_fits_complete_canvas_inside_current_screen(self):
        self.assertIn('function fitNewsLineageToViewport(panel)', SCRIPT)
        self.assertIn('viewport.clientWidth / canvasWidth', SCRIPT)
        self.assertIn('availableHeight / canvasHeight', SCRIPT)
        self.assertIn('window.innerHeight - viewportTop - 12', SCRIPT)
        self.assertIn('data-news-lineage-stage', SCRIPT)
        self.assertIn('data-lineage-width="${lineageWidth}"', SCRIPT)
        self.assertIn('data-lineage-height="${lineageHeight}"', SCRIPT)
        self.assertIn('自动适配当前屏幕的完整情报生成流程图', SCRIPT)
        self.assertIn('.news-lineage-viewport {\n  position: relative;', STYLE)
        self.assertIn('  display: flex;', STYLE)
        self.assertIn('  justify-content: center;', STYLE)
        self.assertIn('  overflow: hidden;', STYLE)
        self.assertIn('.news-lineage-stage { position: relative;', STYLE)
        self.assertIn('transform-origin: left top;', STYLE)
        self.assertNotIn('overflow: auto hidden', STYLE)

    def test_news_lineage_uses_semantic_health_colours_instead_of_node_type_colours(self):
        self.assertIn('const runHealth = (run) =>', SCRIPT)
        self.assertIn('const combinedRunHealth = (items) =>', SCRIPT)
        self.assertIn('function authoritativeStrategicNewsRuns(attempts)', SCRIPT)
        self.assertIn('strategicNewsRunRank(run)', SCRIPT)
        self.assertIn('run?.operational_summary?.readback_verified === true', SCRIPT)
        self.assertIn('const runs = authoritativeStrategicNewsRuns(attemptRuns);', SCRIPT)
        self.assertIn('unit: newsRun.run_status === "running" ? "" : "次权威新闻任务"', SCRIPT)
        self.assertIn('`只负责触发 · ${attemptRuns.length} 次任务尝试`', SCRIPT)
        self.assertIn('data-health="${esc(node.health?.key || "unknown")}"', SCRIPT)
        self.assertIn('健康状态${esc(node.health?.label || "无记录")}', SCRIPT)
        for label in ("正常", "运行中", "警告", "异常", "无记录"):
            self.assertIn(label, SCRIPT)
        for health in ("healthy", "running", "warning", "critical", "unknown"):
            self.assertIn(f".news-lineage.is-global .news-lineage-node.is-health-{health}", STYLE)
        self.assertNotIn('node.tone', SCRIPT)

    def test_news_lineage_accepts_recovered_completed_stage_evidence(self):
        self.assertIn('const completedFromSummary = {', SCRIPT)
        self.assertIn('dedupe: runCompleted && summary.history_duplicates !== undefined && summary.new_count !== undefined', SCRIPT)
        self.assertIn('write: runCompleted && summary.readback_verified === true', SCRIPT)
        self.assertIn('push: notificationCompleted', SCRIPT)
        self.assertIn('(?:语义去重完成|历史语义去重)', SCRIPT)
        self.assertIn('notificationStatus === "sent" ? "正式群卡片已发送"', SCRIPT)
        self.assertIn('运行完成摘要已确认该阶段完成', SCRIPT)
        self.assertIn("function logLineMatching(content, pattern)", SCRIPT)
        self.assertIn('dedupe: logLineMatching(content, /(?:^|\\]\\s*)(?:语义去重完成|历史语义去重)：/)', SCRIPT)
        self.assertNotIn('dedupe: logLine(content, "语义去重完成") || logLine(content, "历史语义去重")', SCRIPT)

    def test_news_lineage_marks_only_evidence_backed_or_gated_llm_route_impacts(self):
        self.assertIn("function activeLineageRouteAssessments(selectedDate)", SCRIPT)
        self.assertIn("function newsLineageEdgeStatus(from, to, nodesByKey, selectedDate, routeAssessments)", SCRIPT)
        self.assertIn('Number(task.route_assessment_version || 0) >= 1', SCRIPT)
        self.assertIn('impact === "interrupted" && confidence !== "high"', SCRIPT)
        self.assertIn('selectedDate !== hktCalendarDate()', SCRIPT)
        self.assertIn('source: "llm-incident"', SCRIPT)
        self.assertIn('source: "run-evidence"', SCRIPT)
        self.assertIn('data-line-state="${esc(line?.key || "unknown")}"', SCRIPT)
        self.assertIn('data-news-lineage-state', SCRIPT)
        self.assertIn('受影响线路 · LLM 受限复核', SCRIPT)
        self.assertIn('仅高置信度中断可触发红色断线', SCRIPT)
        self.assertIn('task.source === "project-monitor"', SCRIPT)
        self.assertIn("renderNews();", SCRIPT)
        self.assertIn(".news-lineage-edge.is-line-interrupted > path:first-of-type", STYLE)
        self.assertIn("stroke-dasharray: 16 11", STYLE)
        self.assertIn("marker-end: url(#newsLineageArrowRed)", STYLE)
        self.assertIn(".news-lineage-edge.is-line-degraded", STYLE)
        self.assertIn(".news-line-health-legend", STYLE)
        self.assertIn('<span class="is-line-scheduled"><i></i>定时</span>', SCRIPT)
        self.assertIn('<span class="is-line-feedback"><i></i>回流</span>', SCRIPT)
        self.assertIn("#newsLineageArrowRoutine path", STYLE)
        self.assertIn("#newsLineageArrowFeedback path", STYLE)
        self.assertIn("marker-end: url(#newsLineageArrowRoutine)", STYLE)
        self.assertIn("marker-end: url(#newsLineageArrowFeedback)", STYLE)
        self.assertIn(".news-line-health-legend .is-line-scheduled", STYLE)
        self.assertIn(".news-line-health-legend .is-line-feedback", STYLE)
        self.assertIn(".fault-route-impact", STYLE)

    def test_news_lineage_locates_running_work_on_one_specific_node(self):
        self.assertIn("function activeNewsStage(stages)", SCRIPT)
        self.assertIn("function activeNewsStageNodeKey(stageKey)", SCRIPT)
        self.assertIn('gate: "news-search"', SCRIPT)
        self.assertIn('write: "news-output"', SCRIPT)
        self.assertIn('const currentStrategicStage = strategicHealth.key === "running" ? activeNewsStage(stages) : null;', SCRIPT)
        self.assertIn('`当前阶段：${currentStrategicStage.label}`', SCRIPT)
        self.assertIn('`已触发 · 当前执行：${activeNewsStageNodeLabel(currentStrategicStage.key)}', SCRIPT)
        self.assertIn('当前执行已定位在“${runningNode.label}”节点；未发现线路异常证据。', SCRIPT)
        self.assertNotIn('label: "传输中"', SCRIPT)
        self.assertNotIn('["interrupted", "degraded", "at-risk", "running"].includes(line?.key)', SCRIPT)

    def test_news_lineage_uses_semantic_svg_status_icons(self):
        self.assertIn("function lineageStatusIcon(status)", SCRIPT)
        for status in ("healthy", "running", "warning", "critical", "unknown", "interrupted", "degraded", '"at-risk"'):
            self.assertIn(f"{status}:", SCRIPT)
        self.assertIn('lineageStatusIcon(node.health?.key || "unknown")', SCRIPT)
        self.assertIn("lineageStatusIcon(line.key)", SCRIPT)
        self.assertIn(".news-lineage-status-icon", STYLE)
        self.assertNotIn(".news-lineage-edge-state.is-running", STYLE)


if __name__ == "__main__":
    unittest.main()
